-- MySQL Script generated by MySQL Workbench
-- Thu Mar 22 11:11:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SignIn_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SignIn_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `age` INT(3) NOT NULL,
  `education` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `SignIn_info_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admin_SignIn_info1_idx` (`SignIn_info_id` ASC),
  CONSTRAINT `fk_admin_SignIn_info1`
    FOREIGN KEY (`SignIn_info_id`)
    REFERENCES `mydb`.`SignIn_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scholar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scholar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `SignIn_info_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_scholar_SignIn_info1_idx` (`SignIn_info_id` ASC),
  CONSTRAINT `fk_scholar_SignIn_info1`
    FOREIGN KEY (`SignIn_info_id`)
    REFERENCES `mydb`.`SignIn_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course_scholar_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course_scholar_list` (
  `id` INT NOT NULL,
  `scholar_id` INT NOT NULL,
  `registration_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Course_list_scholar1_idx` (`scholar_id` ASC),
  CONSTRAINT `fk_Course_list_scholar1`
    FOREIGN KEY (`scholar_id`)
    REFERENCES `mydb`.`Scholar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `SignIn_info_id` INT NOT NULL,
  `spetialization` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Teacher_SignIn_info1_idx` (`SignIn_info_id` ASC),
  CONSTRAINT `fk_Teacher_SignIn_info1`
    FOREIGN KEY (`SignIn_info_id`)
    REFERENCES `mydb`.`SignIn_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `theme` VARCHAR(45) NOT NULL,
  `rating` INT(5) NOT NULL,
  `duration` TIME(5) NOT NULL,
  `Course_list_id` INT NOT NULL,
  `Teacher_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Course_Course_list1_idx` (`Course_list_id` ASC),
  INDEX `fk_Course_Teacher1_idx` (`Teacher_id` ASC),
  CONSTRAINT `fk_Course_Course_list1`
    FOREIGN KEY (`Course_list_id`)
    REFERENCES `mydb`.`Course_scholar_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Teacher1`
    FOREIGN KEY (`Teacher_id`)
    REFERENCES `mydb`.`Teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `duration` TIME(5) NOT NULL,
  `Course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Subject_Course1_idx` (`Course_id` ASC),
  CONSTRAINT `fk_Subject_Course1`
    FOREIGN KEY (`Course_id`)
    REFERENCES `mydb`.`Course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mark` INT(5) NOT NULL,
  `theme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lesson` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `theme` VARCHAR(45) NOT NULL,
  `duration` TIME(5) NOT NULL,
  `Subject_id` INT NOT NULL,
  `Task_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Lesson_Subject1_idx` (`Subject_id` ASC),
  INDEX `fk_Lesson_Task1_idx` (`Task_id` ASC),
  CONSTRAINT `fk_Lesson_Subject1`
    FOREIGN KEY (`Subject_id`)
    REFERENCES `mydb`.`Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lesson_Task1`
    FOREIGN KEY (`Task_id`)
    REFERENCES `mydb`.`Task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher_feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher_feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mark` INT(5) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `Teacher_id` INT NOT NULL,
  `Scholar_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Teacher_feedback_Teacher1_idx` (`Teacher_id` ASC),
  INDEX `fk_Teacher_feedback_Scholar1_idx` (`Scholar_id` ASC),
  CONSTRAINT `fk_Teacher_feedback_Teacher1`
    FOREIGN KEY (`Teacher_id`)
    REFERENCES `mydb`.`Teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_feedback_Scholar1`
    FOREIGN KEY (`Scholar_id`)
    REFERENCES `mydb`.`Scholar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course_feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course_feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mark` INT(5) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `Scholar_id` INT NOT NULL,
  `Subject_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Course_feedback_Scholar1_idx` (`Scholar_id` ASC),
  INDEX `fk_Course_feedback_Subject1_idx` (`Subject_id` ASC),
  CONSTRAINT `fk_Course_feedback_Scholar1`
    FOREIGN KEY (`Scholar_id`)
    REFERENCES `mydb`.`Scholar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_feedback_Subject1`
    FOREIGN KEY (`Subject_id`)
    REFERENCES `mydb`.`Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
